//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webhi2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dept
    {
        public int deptid { get; set; }
        public string deptname { get; set; }
        public string location { get; set; }
    }
}
