//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webhi2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class job
    {
        public string jobid { get; set; }
        public string job_title { get; set; }
        public Nullable<int> minsalary { get; set; }
        public Nullable<int> maxsalary { get; set; }
    }
}
